name: colcatrufis
description: Aplicación de trufis Colcapirhua

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  url_launcher: ^6.3.0
  
  shared_preferences: ^2.2.3
  
  flutter_map_geojson: ^1.0.8 # Para manejar archivos GeoJSON
  # Mapa
  flutter_map: ^7.0.2
  latlong2: ^0.9.0     # Para trabajar con coordenadas en el mapa
  # Ubicación
  geolocator: ^11.0.1   # Para obtener la ubicación del usuario
  
  # HTTP
  http: ^1.6.0         # Actualizamos la versión de http a la recomendada

  # Estado
  provider: ^6.1.1      # Gestión del estado de la aplicación
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  # Para buenas prácticas de codificación

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/    # Asegúrate de que las imágenes estén en la carpeta correcta
    - assets/geojson/colcapirhua.geojson  # Para que las imágenes funcionen
  generate: true
